### ISSUE TITLE
Feature Request / Suggestion: QOL improvements on WUI

### ISSUE THREAD

**Issue by theniwo** [pucherot/Pi.Alert#16]
Hi I noticed some things while using the webui that may be addressed in future updates.

* The `Show x Entries` menu is not saved when the page is refreshed or when changed back to the devices overview.
* Same goes for sorting.
* Add an `All` option to the `Show x Entries` menu
* Option to filter for a time range like in pihole.
* When opening a device it would be nice if the default page was Details instead of Presence. Maybe include a user custom setting in a future settings page?
* Adding an Ok button to the Details page that closes the page and goes back to the Devices overview.
* No message box that says "Device updated successfully" please. Please only report errors that way.
* Report if there are unsaved changes when trying to leave the configuration page.
* Option to delete unwanted entries and other things like groups from the database via webui.
* Option to only show favorites in any tab like the presence tab or overview to declutter.
* Option to blacklist, hide or delete host entries.
* Import / Export / Backup Function for database entries.
* Option to trigger a scan 1 manually from the wui.
* Add Device Type Singleboard Computer (SBC) / Raspberry Pi (RPI)
* Add Location field (Door, Basement, etc.)
* Customizable Devices Overview columns. (Like adding Scan cycle, configured alerts, comments, etc)
* Button to mark new devices as "known" i.e. not new anymore

**Comment by pucherot** [comment]
wow, a nice and huge list of improvements.
All very interesting and with all the sense in the world.

I will study them to incorporate progressively.

BR

**Comment by pucherot** [comment]
### Done (available in next version)
- [x] The Show x Entries menu is not saved when the page is refreshed or when changed back to the devices overview. **Done**
- [x] Same goes for sorting. **Done**
- [x] Add an All option to the Show x Entries menu **Done**
- [x] When opening a device it would be nice if the default page was Details instead of Presence. Maybe include a user custom setting in a future settings page?. **Done. Now the last panel visited is saved. Next time this page will be the default panel**
- [x] No message box that says "Device updated successfully" please. Please only report errors that way. **Done**
- [x] Option to delete unwanted entries and other things like groups from the database via webui. **Done / Now is possible to delete Devices. Lists of Groups, Types, ... are updated automatically**
- [x] Option to blacklist, hide or delete host entries. **Done / Now is possible to delete Devices** 
- [x] Add Device Type Singleboard Computer (SBC) / Raspberry Pi (RPI). **Done**
- [x] Add Location field (Door, Basement, etc.)
- [x] Button to mark new devices as "known" i.e. not new anymore. **Done**

### Backlog
- [ ] Option to filter for a time range like in pihole. **backlog**
- [ ] Report if there are unsaved changes when trying to leave the configuration page.  **backlog**
- [ ] Option to only show favorites in any tab like the presence tab or overview to declutter. **backlog**
- [ ] Import / Export / Backup Function for database entries. **backlog**
- [ ] Option to trigger a scan 1 manually from the wui. **backlog**
- [ ] Customizable Devices Overview columns. (Like adding Scan cycle, configured alerts, comments, etc) **backlog**

### Rejected
- [ ] ~~Adding an Ok button to the Details page that closes the page and goes back to the Devices overview.~~ **Rejected / You can click "Devices" in the lateral menu**
