### ISSUE TITLE
Question: Is DHCP enabled on the PiHole strictly needed?

### ISSUE THREAD

**Issue by irnutsmurt** [pucherot/Pi.Alert#24]
My router (Unifi Dream Machine Base) has more advanced DHCP capabilities than what the PiHole offers that I take advantage of, I was just wondering if I can I run this without DHCP enabled? My PiHole is able to get the list of devices using it because I do forward DNS to it. Just wanted to check before going down that rabbit hole.

**Comment by Niemiz** [comment]
I've about same question, instead of me creating new I hope it's okay I add questions to this one.

I forgot follow this step at very first, but then I'm sure I did disable DHCP in my router and enabled DHCP in pi.hole as well renewed my computers IP.

pi.alert did work the first night I installed it, loaded in all my devices and was able notify when I disconnected an IP camera as well my phone.

Now days later I've noticed - it hasn't been logging anything in 'Events' ever since despite my devices like phone and now IP camera, and other items has been disconnected for some time and re-connected hours later.

I found out my DHCP on router were active when I now double checked, as well my DHCP on pi.hole wasn't. So now I have tried again, been restarting router, pi.hole as well computer and other devices. My computer has now got new IP and in pi.hole it doesn't show me the local IP addresses anymore in query (instead it shows it's name set in router with .lan at end, which it hasn't before).
Well the thing is it still doesn't work for me as of now. Idk if it's the DHCP setup I had in beginning that caused it and if I'd need reinstall or something else?

**Comment by pucherot** [comment]
> Mi router (Unifi Dream Machine Base) tiene capacidades DHCP más avanzadas que lo que ofrece pihole que aprovecho, me preguntaba si puedo ejecutar esto sin DHCP habilitado? Mi PiHole es capaz de obtener la lista de dispositivos que lo utilizan porque reenvío DNS a él. Sólo quería comprobarlo antes de bajar por ese agujero de conejo.

Of course, you can.
Note to correctly configure pyalert.conf values:
~~~
PIHOLE_ACTIVE     = True
DHCP_ACTIVE       = False
~~~

**Comment by pucherot** [comment]
> I've about same question, instead of me creating new I hope it's okay I add questions to this one.
> 
> I forgot follow this step at very first, but then I'm sure I did disable DHCP in my router and enabled DHCP in pi.hole as well renewed my computers IP.
> 
> pi.alert did work the first night I installed it, loaded in all my devices and was able notify when I disconnected an IP camera as well my phone.
> 
> Now days later I've noticed - it hasn't been logging anything in 'Events' ever since despite my devices like phone and now IP camera, and other items has been disconnected for some time and re-connected hours later.
> 
> I found out my DHCP on router were active when I now double checked, as well my DHCP on pi.hole wasn't. So now I have tried again, been restarting router, pi.hole as well computer and other devices. My computer has now got new IP and in pi.hole it doesn't show me the local IP addresses anymore in query (instead it shows it's name set in router with .lan at end, which it hasn't before).
> Well the thing is it still doesn't work for me as of now. Idk if it's the DHCP setup I had in beginning that caused it and if I'd need reinstall or something else?

- Pi.hole DHCP server is optional, you can use your current DHCP server
- If you want to use Pi.hole as DNS Server you must configure your DHCP with the correct DNS (Pi.hole IP adress)
- Pi.Alert use 3 methods to scan the network. Methods 2 and 3 use Pi.hole DNS and DHCP server, but method 1 use arp-scan. Check if you crontab is correct and check de log:
~~~
crontab -l
cat ~/pialert/log
~~~

**Comment by pucherot** [comment]
> > Mi router (Unifi Dream Machine Base) tiene capacidades DHCP más avanzadas que lo que ofrece pihole que aprovecho, me preguntaba si puedo ejecutar esto sin DHCP habilitado? Mi PiHole es capaz de obtener la lista de dispositivos que lo utilizan porque reenvío DNS a él. Sólo quería comprobarlo antes de bajar por ese agujero de conejo.
> 
> Of course, you can.
> Note to correctly configure pyalert.conf values:
> 
> ```
> PIHOLE_ACTIVE     = True
> DHCP_ACTIVE       = False
> ```

Is OK now?
