### ISSUE TITLE
SUGGESTION: don't rely only on arp_scan to determine if device is up/down/connected/disconnected

### ISSUE THREAD

**Issue by stevehoek** [pucherot/Pi.Alert#79]
There are many devices that don't respond to arp scan commands: smart outlets, Ring cameras, some Apple devices, etc.

If PiAlert is configured to use the DHCP server's lease table, it could use that to determine if a device is up/online based on if it has a valid lease.  This could be configured on a per-device basis for problematic devices.

Currently it appears the DHCP server's lease table is only used to discover new devices (same with PiHole network table), not determine their status.

**Comment by stevehoek** [comment]
Thinking more on this... 

- the DHCP lease table could let you know if the MAC that is missing from the ARP scan still has the same IP as it did the last time it was discovered.  
- if it does, then a ping could be executed; if it responds, the device can be assumed to be still connected
    - a device could have changed IP, but the MAC can be the key and use the latest IP from the DHCP lease table
    - some devices don't respond to ping either.  in my testing of Ring cameras and iDevices smart outlets, they do respond to ping but are hit and miss in the ARP scan

**Comment by pucherot** [comment]
A DHCP lease does not indicate that the device is active, it only indicates that at a certain moment it requested an IP from the DPCP server. Indeed, DHCP leases are only used to identify devices on the network, not to detect whether or not they are connected at any given time.

On the contrary, with Pi-hole is possible to determine if a device is active, checking the queries to the DNS server. and this is the use of Pi-Alert.

In the other hand, ping is not a valid mechanism to check if a device is active. Many devices do not respond to ping commands because they are considered unsafe.

**Comment by stevehoek** [comment]
True, DHCP is not the right answer to determine online status.

I really like your app, but arp-scan on my network (around 150 devices, half wireless, half wired) is just not reliable.  It constantly is flagging devices as offline just because they don't respond to arp-scan reliably, or is a wifi device that is sleeping but still online, etc.  

The issue for me with Pi-hole network table is that a device such as a wifi smart plug, one that does not reliably respond to arp-scan, may be making a DNS query only once a day or even once a week, so it is online but but by the logic used in checking the last Pi-hole query vs the scan cycle, Pi.Alert is not counting it as online.

I've made a fork of your code and have done the work to hook it up to my router's API (UniFi) so that it can interrogate the router's client list directly and use that as a primary source of truth for devices on the network instead of arp-scan.
So far it is working well and is at the level of accuracy I would expect for my network.
